{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "edgecdnx-controller.serviceAccountName" . }}
  labels:
    {{- include "edgecdnx-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - locations
  - prefixlists
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - locations/finalizers
  - prefixlists/finalizers
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.edgecdnx.com
  resources:
  - locations/status
  - prefixlists/status
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - "acme.cert-manager.io"
  resources:
  - challenges
  - orders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "cert-manager.io"
  resources:
  - certificates
  - certificaterequests
  - certificatesigningrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- if eq .Values.role "cache-controller" }}
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "edgecdnx-controller.serviceAccountName" . }}
  labels:
    {{- include "edgecdnx-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "edgecdnx-controller.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "edgecdnx-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
