apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ include "tls-cert-thrower.fullname" . }}
  labels:
    {{- include "tls-cert-thrower.labels" . | nindent 4 }}
spec:
  template:
    serviceAccountName: {{ include "tls-cert-thrower.serviceAccountName" . }}
  dependencies:
    - name: secret-event-dep
      eventSourceName: {{ include "tls-cert-thrower.fullname" . }}
      eventName: secret-events
  eventBusName: {{ include "tls-cert-thrower.fullname" . }}
  triggers:
    - template:
        name: throw-tls-cert
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: applications
          operation: create
          parameters:
            - src:
                dependencyName: secret-event-dep
                dataKey: body
              dest: spec.source.helm.valuesObject.resources[0]
            - src:
                dependencyName: secret-event-dep
                dataTemplate: "mon-tls-key-{{`{{.Input.body.metadata.annotations.target | nospace | lower }}`}}"
              dest: metadata.name
            - src:
                dependencyName: secret-event-dep
                dataKey: body.metadata.namespace
              dest: metadata.namespace
            # - src:
            #     dependencyName: secret-event-dep
            #     dataKey: body.metadata.name
            #   dest: metadata.ownerReferences[0].name
            # - src:
            #     dependencyName: secret-event-dep
            #     dataKey: body.metadata.uid
            #   dest: metadata.ownerReferences[0].uid
            - src:
                dependencyName: secret-event-dep
                dataKey: body.metadata.annotations.target
              dest: spec.destination.server
            - src:
                dependencyName: secret-event-dep
                dataKey: body.metadata.namespace
              dest: spec.destination.namespace
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Application
              metadata:
                name: "{{`{{ .Input.body.metadata.name }}`}}"
                namespace: "{{`{{ .Input.body.metadata.namespace }}`}}"
                # ownerReferences:
                #   - apiVersion: v1
                #     kind: Secret
                #     name: "{{`{{ .Input.body.metadata.name }}`}}"
                #     uid: "{{`{{ .Input.body.metadata.uid }}`}}"
                #     controller: true
                #     blockOwnerDeletion: true
              spec:
                project: default
                source:
                  repoURL: https://edgecdn-x.github.io/helm-charts
                  chart: resource-thrower
                  targetRevision: 0.1.0
                  helm:
                    releaseName: tls-cert-thrower
                    valuesObject:
                      resources: ["dummy"]
                destination:
                  namespace: "{{`{{ .Input.body.metadata.namespace }}`}}"
                  server: "{{`{{ .Input.body.metadata.annotations.target }}`}}"
                syncPolicy:
                  automated:
                    selfHeal: true

