apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infrastructure-location.fullname" . }}
  labels:
    {{- include "infrastructure-location.labels" . | nindent 4 }}
    edgecdnx.com/location: "true"
data:
  infrastructure-location-{{ .Values.name }}.yaml: |
    version: {{ .Values.version | quote }}
    name: {{ .Values.name | quote }}
    location:
      {{- toYaml .Values.location | nindent 6 }}
