apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infrastructure-location.fullname" . }}
  labels:
    {{- include "infrastructure-location.labels" . | nindent 4 }}
    edgecdnx.com/location: "true"
data:
  infrastructure-location-{{ .Values.name }}.yaml: |
    {{- toYaml .Values.location | nindent 4 }}
