apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "routing-config.fullname" . }}
  labels:
    {{- include "routing-config.labels" . | nindent 4 }}
    edgecdnx.com/routes: "true"
data:
  routing-config-{{ .Values.routing.location }}.yaml: |
    {{- toYaml .Values.routing | nindent 4 }}
