{
 "title": "EdgeCDN-X Analytics",
 "description": "All Sorts of Analytics output for services",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "vhost",
    "label": "vhost",
    "query": "SELECT DISTINCT vhost FROM analytics WHERE $__timeFilter(created_at);"
   },
   {
    "name": "location",
    "label": "Location",
    "query": "SELECT DISTINCT location FROM analytics WHERE $__timeFilter(created_at);"
   }
  ]
 },
 "panels": [
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "dataset": "app",
     "rawSql": "SELECT\n  time_bucket('$__interval', created_at) AS time,\n  vhost,\n  location,\n  (SUM(bytes_sent) * 8) / (EXTRACT(EPOCH FROM '$__interval'::interval) * 1000000) AS mbps\nFROM analytics\nWHERE $__timeFilter(created_at)\n  AND vhost IN ($vhost)\n  AND location IN ($location)\nGROUP BY time, vhost, location\nORDER BY time, vhost, location;"
    }
   ]
  },
  {
   "title": "Total Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dataset": "app",
     "rawSql": "SELECT\n  vhost,\n  SUM(bytes_sent) :: float as bytes_sent,\n  SUM(upstream_bytes) :: float as upstream_bytes\nFROM\n  analytics\nWHERE\n  $__timeFilter(created_at)\n  AND vhost IN ($vhost)\nGROUP BY\n  vhost"
    }
   ]
  },
  {
   "title": "Hit ratio",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "app",
     "rawSql": "SELECT\n  vhost,\n  (SUM(bytes_sent) - SUM(upstream_bytes))::float / NULLIF(SUM(bytes_sent), 0) AS cache_hit_ratio\nFROM\n  analytics\nWHERE\n  $__timeFilter(created_at)\n  AND vhost IN ($vhost)\nGROUP BY vhost"
    }
   ]
  },
  {
   "title": "Data sent / received [MB] - ${location}",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "repeat": "location",
   "targets": [
    {
     "dataset": "app",
     "rawSql": "SELECT\n  vhost,\n  location,\n  SUM(bytes_sent) :: float / 1024 / 1024 AS bytes_sent_mb,\n  SUM(upstream_bytes) :: float / 1024 / 1024 AS upstream_bytes_mb\nFROM\n  analytics\nWHERE\n  $__timeFilter(created_at)\n  AND vhost IN ($vhost)\n  AND location IN ($location)\nGROUP BY\n  vhost,\n  location\nORDER BY\n  vhost,\n  location;"
    }
   ]
  }
 ]
}