apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: services.infrastructure.edgecdnx.com
spec:
  conversion:
    strategy: None
  group: infrastructure.edgecdnx.com
  names:
    kind: Service
    listKind: ServiceList
    plural: services
    singular: service
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Service is the Schema for the services API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ServiceSpec defines the desired state of Service.
            properties:
              cache:
                type: string
              customer:
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                type: object
              domain:
                type: string
              name:
                type: string
              originType:
                enum:
                - s3
                - static
                type: string
              staticOrigins:
                items:
                  properties:
                    hostHeader:
                      type: string
                    port:
                      type: integer
                    scheme:
                      enum:
                      - Http
                      - Https
                      type: string
                    upstream:
                      type: string
                  type: object
                type: array
            required:
            - customer
            type: object
          status:
            description: ServiceStatus defines the observed state of Service.
            properties:
              status:
                enum:
                - Healthy
                - Progressing
                - Degraded
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
