{{- range .Values.metallb.addressPools }}
{{- if .l2advertisement }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ include "metallb-config.fullname" $ }}-{{ .name }}
  labels:
    {{- include "metallb-config.labels" $ | nindent 4 }}
spec:
  ipAddressPools:
    - {{ include "metallb-config.fullname" $ }}-{{ .name }}
{{- end }}
{{- end }}